spec:
  replicas: 1
  template:
    spec:
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
          name: my-main-container
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
